version: "1"

services:
  app:
    image: '${DOCKER_IMAGE_NAME:-parking-app-ms}:${DOCKER_IMAGE_TAG:-latest}'
    tty: true
    container_name: parking_app
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python3 manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/code
    ports:
      - 8001:8001
    restart: always
